"""Central metadata type registry for Configurator and EDT exports."""

TYPE_DIRS = {
    "Catalogs": "Catalog",
    "Documents": "Document",
    "CommonModules": "CommonModule",
    "InformationRegisters": "InformationRegister",
    "AccumulationRegisters": "AccumulationRegister",
    "AccountingRegisters": "AccountingRegister",
    "CalculationRegisters": "CalculationRegister",
    "Enums": "Enum",
    "Constants": "Constant",
    "ChartsOfCharacteristicTypes": "ChartOfCharacteristicTypes",
    "ChartsOfAccounts": "ChartOfAccounts",
    "ChartsOfCalculationTypes": "ChartOfCalculationTypes",
    "BusinessProcesses": "BusinessProcess",
    "Tasks": "Task",
    "Reports": "Report",
    "DataProcessors": "DataProcessor",
    "CommonForms": "CommonForm",
    "CommonPictures": "CommonPicture",
    "Languages": "Language",
    "SessionParameters": "SessionParameter",
    "CommonCommands": "CommonCommand",
    "Subsystems": "Subsystem",
    "Roles": "Role",
    "ScheduledJobs": "ScheduledJob",
    "EventSubscriptions": "EventSubscription",
    "DefinedTypes": "DefinedType",
    "FunctionalOptions": "FunctionalOption",
    "FunctionalOptionsParameters": "FunctionalOptionsParameter",
    "HTTPServices": "HTTPService",
    "WebServices": "WebService",
    "WSReferences": "WSReference",
    "XDTOPackages": "XDTOPackage",
}
MANAGERS = {
    "Справочники": "Catalog",
    "Catalogs": "Catalog",
    "Документы": "Document",
    "Documents": "Document",
    "РегистрыСведений": "InformationRegister",
    "InformationRegisters": "InformationRegister",
    "РегистрыНакопления": "AccumulationRegister",
    "AccumulationRegisters": "AccumulationRegister",
    "РегистрыБухгалтерии": "AccountingRegister",
    "РегистрыРасчета": "CalculationRegister",
}
QUERY_TYPES = {
    "Справочник": "Catalog",
    "Catalog": "Catalog",
    "Документ": "Document",
    "Document": "Document",
    "РегистрСведений": "InformationRegister",
    "InformationRegister": "InformationRegister",
    "РегистрНакопления": "AccumulationRegister",
    "AccumulationRegister": "AccumulationRegister",
    "РегистрБухгалтерии": "AccountingRegister",
    "РегистрРасчета": "CalculationRegister",
}
CHILD_TYPES = {
    "Attribute",
    "Dimension",
    "Resource",
    "TabularSection",
    "EnumValue",
    "AddressingAttribute",
    "URLTemplate",
    "Method",
    "Operation",
    "Parameter",
}
EDT_CHILD_TYPES = {
    "attributes": "Attribute",
    "tabularsections": "TabularSection",
    "dimensions": "Dimension",
    "resources": "Resource",
    "enumvalues": "EnumValue",
    "addressingattributes": "AddressingAttribute",
}
REFERENCE_TYPES = {
    "CatalogRef": "Catalog",
    "DocumentRef": "Document",
    "InformationRegisterRecord": "InformationRegister",
    "AccumulationRegisterRecord": "AccumulationRegister",
    "CatalogObject": "Catalog",
    "DocumentObject": "Document",
    "InformationRegisterRecordSet": "InformationRegister",
    "AccumulationRegisterRecordSet": "AccumulationRegister",
    "DefinedType": "DefinedType",
    "EnumRef": "Enum",
    "ChartOfCharacteristicTypesRef": "ChartOfCharacteristicTypes",
    "ChartOfAccountsRef": "ChartOfAccounts",
    "ChartOfCalculationTypesRef": "ChartOfCalculationTypes",
    "BusinessProcessRef": "BusinessProcess",
    "TaskRef": "Task",
}
